name: Daily Kids Video Pipeline

on:
  schedule:
    # 9:30 AM IST = 04:00 UTC
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Build llama.cpp (CMake)
        run: |
          git clone https://github.com/ggml-org/llama.cpp.git
          cd llama.cpp
          cmake -B build
          cmake --build build --config Release


      - name: Generate script
        run: python3 scripts/generate_script.py

      - name: Generate TTS
        run: python3 scripts/generate_tts.py
        env:
          TTS_MODEL: tts_models/en/ljspeech/tacotron2-DDC

      - name: Generate Video Clip
        run: python3 scripts/generate_video.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_MODEL: YourUser/HunyuanVideo-GGUF

      - name: Assemble Final Video
        run: python3 scripts/assemble_video.py
        env:
          BGM_PATH: assets/bgm.mp3

      - name: Upload to YouTube
        run: python3 scripts/upload_video.py
        env:
          YT_ACCESS_TOKEN: ${{ secrets.YT_ACCESS_TOKEN }}
          VIDEO_TITLE: "ABC Rhymes for Kids – ${{ github.run_id }}"
          VIDEO_DESCRIPTION: "Bright, fun, animated alphabet and rhymes video."
          VIDEO_PRIVACY: public
